apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-sheets-sync-exec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-sheets-sync-exec
subjects:
  - kind: ServiceAccount
    name: argocd-sheets-sync
    namespace: argocd
